#!/bin/sh
# tools/vectors.sh
# Rewrite of tools/vectors.pl to Bash.
# Usage: ./tools/vectors.sh > vectors.S

printf '%s\n' '# generated by vectors.sh - do not edit'
printf '%s\n' '# handlers'
printf '%s\n' '.globl alltraps'

i=0
while [ "$i" -lt 256 ]; do
  printf '.globl vector%d\n' "$i"
  printf 'vector%d:\n' "$i"

  if [ "$i" -ne 8 ] && { [ "$i" -lt 10 ] || [ "$i" -gt 14 ]; } && [ "$i" -ne 17 ]; then
    printf '  pushl $0\n'
  fi

  printf '  pushl $%d\n' "$i"
  printf '  jmp alltraps\n'
  i=$((i + 1))
done

printf '\n%s\n' '# vector table'
printf '%s\n' '.data'
printf '%s\n' '.globl vectors'
printf '%s\n' 'vectors:'

i=0
while [ "$i" -lt 256 ]; do
  printf '  .long vector%d\n' "$i"
  i=$((i + 1))
done
